### ISSUE TITLE
Ticker on react native 0.40.0

### ISSUE THREAD

**Issue by wanshijie3** [browniefed/react-native-ticker#12]
Recently I need to use Ticker in version 0.40.0, but there is a problem, the number can not be displayed properly,
 the error message is 
'null is not an object (evaluating e.nativeEvent.layout'), 
I think it is a problem of nativeEvent, according to react Native documentation added 'e.persist()' before using 'e.nativeEvent', but still does not display properly

I noticed the version "prop-types" used by Ticker: "^15.6.0", I am using 15.5.10, but I don't know where the difference is.

react-native:0.40.0
Prop-Types 15.5.10

**Comment by browniefed** [comment]
Update your React Native, I have not attempted to support anything that old.
