### ISSUE TITLE
TypeError: Children.map(...).flat is not a function

### ISSUE THREAD

**Issue by calebdre** [browniefed/react-native-ticker#28]
I get this error in production:
`File "node_modules/react-native-ticker/index.js", line 90, col 8, in Component`

This seems to happen on app startup when my component is first trying to mount the `Ticker` component

**Comment by danielvportlandia** [comment]
I was having the same issue on Android when mounting the Ticker component. iOS was fine and the problem didn't occur on Android if the remote debugger was active. The following patch works for me.

index.js, line 82;
```
    let measureStrings = Children.map(children, child => { // change from const
        if (typeof child === "string" || typeof child === "number") {
            return splitText(`${child}`);
        }
        else {
            //@ts-ignore
            return child.props && child.props.rotateItems;
        }
    });
    if (measureStrings && typeof measureStrings.flat === "function") measureStrings = measureStrings.flat(); // add this
```

**Comment by calebdre** [comment]
@danielvportlandia awesome - have you made other patches/fixes? If so you should make a pull request! Otherwise I'll make one with your above change

**Comment by bencIsTheGoat** [comment]
+1 on this, nice fix!

**Comment by bencIsTheGoat** [comment]
@browniefed I'm attempted to open a PR for this fix, can you allow so prs can be opened?

**Comment by browniefed** [comment]
Wait you can't open a PR? I'm so confused. let me take a look

**Comment by browniefed** [comment]
@bcutler94 You should be able to, I don't have any restrictions on. Not sure what's up

**Comment by bencIsTheGoat** [comment]
@browniefed Shoot, I must be doing it wrong. Do you mind verifying my steps? ...
1) Clone repo
2) branch of master
3) git add, commit changes
4) attempt to set upstream of local branch (this is where it fails)
5) git push
6) open pr in github

**Comment by browniefed** [comment]
You need to fork the repo above. So click on `fork` in the top right corner.
Then clone locally, push up, and open a PR.

**Comment by bencIsTheGoat** [comment]
Sweet, okay thanks.

**Comment by freedoms33ker** [comment]
Issue exists on iOS as well. 
Using v3.2.0

**Comment by calebdre** [comment]
Closing - haven't tried 4.0 but i assume it fixes this
