### ISSUE TITLE
Reanimated 2 introduced EasingNode

### ISSUE THREAD

**Issue by nkovacic** [browniefed/react-native-ticker#33]
When using react-native-ticker with reanimated 2.x its throwing alot of warnings: `Easing was renamed to EasingNode in Reanimated 2. Please use EasingNode instead`. 

This migration is required for better reanimated 2.x support: [https://docs.swmansion.com/react-native-reanimated/docs/migration/](https://docs.swmansion.com/react-native-reanimated/docs/migration/)

**Comment by browniefed** [comment]
Added react-native-ticker@5.0.0
