### ISSUE TITLE
Fail Typescript Compile

### ISSUE THREAD

**Issue by Pickleboyonline** [browniefed/react-native-ticker#35]
Hi! 👋 
      
Firstly, thanks for your work on this project! 🙂

Today I used [patch-package](https://github.com/ds300/patch-package) to patch `react-native-ticker@3.2.0` for the project I'm working on.

I am getting these `tsc` compile errors in a standard configered React Native typescript project:
```
node_modules/react-native-ticker/index.tsx:138:36 - error TS2533: Object is possibly 'null' or 'undefined'.

138   const measureStrings: string[] = Children.map(children, child => {
                                       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
139     if (typeof child === "string" || typeof child === "number") {
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
... 
144     }
    ~~~~~
145   }).flat();
    ~~~~

node_modules/react-native-ticker/index.tsx:145:6 - error TS2550: Property 'flat' does not exist on type 'any[]'. Do you need to change your target library? Try changing the 'lib' compiler option to 'es2019' or later.

145   }).flat();
         ~~~~


Found 2 errors.
```
To reproduce, simply create a TS React native project with `npx react-native init MyApp --template react-native-template-typescript` or open an existing one. Add the `react-native-ticker` package and run `yarm tsc`.

Here is the diff that solved my problem:

```diff
diff --git a/node_modules/react-native-ticker/index.tsx b/node_modules/react-native-ticker/index.tsx
index ec63f73..540a9ea 100644
--- a/node_modules/react-native-ticker/index.tsx
+++ b/node_modules/react-native-ticker/index.tsx
@@ -1,3 +1,4 @@
+// @ts-nocheck
 import React, { useRef, useEffect, useState, Children } from "react";
 import { StyleSheet, Text, View, TextStyle, TextProps } from "react-native";
 import Animated, { Easing } from "react-native-reanimated";
```
I used `// @ts-nocheck` as a temporary fix.
<em>This issue body was [partially generated by patch-package](https://github.com/ds300/patch-package/issues/296).</em>

**Comment by browniefed** [comment]
react-native-ticker@5.0.0
