### ISSUE TITLE
misalignment of digits?

### ISSUE THREAD

**Issue by gre** [browniefed/react-native-ticker#7]
I'm trying the library & it seems to me there is a weird y misalignment of digits. any idea why? maybe it does not work with fonts with different digit heights?

<img width="215" alt="capture d ecran 2018-04-20 a 09 42 45" src="https://user-images.githubusercontent.com/211411/39037122-d20092ec-447f-11e8-8289-fd01f2fef240.png">

<img width="204" alt="capture d ecran 2018-04-20 a 09 43 15" src="https://user-images.githubusercontent.com/211411/39037128-d4a28384-447f-11e8-8961-615f8ea97c93.png">
<img width="203" alt="capture d ecran 2018-04-20 a 09 44 31" src="https://user-images.githubusercontent.com/211411/39037129-d4d0f886-447f-11e8-949a-ff0b7ae7d103.png">

fontSize: 24
fontFamily: Open Sans
fontWeight: semi bold

**Comment by browniefed** [comment]
Hmm yeah, I'm guessing that is it. I don't measure individual heights, I only measure a single one.
I'd need to revamp and do a tracking of each height character and track offsets/differences.
That's well beyond the scope of what I am using it for at the moment though.

**Comment by shubhanus** [comment]
Any update on this ???

**Comment by gre** [comment]
@shubhanus you might want to fork the project to your own (and ideally submit a PR 😉) because not sure it's going to move soon, @browniefed probably busy and i would understand ;)

**Comment by browniefed** [comment]
Happy to accept a PR or you'll have to wait a week or so. I'm leaving the company that uses this module and so I'll take a look at how to resolve this. Not going to be easy likely, but doable.

**Comment by browniefed** [comment]
Hey @gre @shubhanus  can you try out v2.1.0, I may have fixed this.

**Comment by browniefed** [comment]
v2.1.1 heh

**Comment by shubhanus** [comment]
@gre 😛 no need of that because **v2.1.1** is working fine. 
**Thanks** 🙂 @browniefed and great work !!!

**Comment by gre** [comment]
holy moly 🙌
