### ISSUE TITLE
Text gets mis-located

### ISSUE THREAD

**Issue by oferRounds** [browniefed/react-native-ticker#8]
Any idea why this might happen?
 
- The right most items should have shown `9`. The two left items does show `0`, but it‘s also mis-located.
- the gray box is the Ticker box; the yellow box is the Text box

This is the relevant code (related to the right-most item): 

render:
```
<Ticker style = { styles.ticker } textStyle = {[ styles.scoreCommonText, styles.firstPlaceText ] }>
     <Tick rotateItems = { this.firstPlaceTickerValues }>
          { this.state.currentScore.firstPlace }
     </Tick>
</Ticker>
```
(for the two left items, `rotateItems` is `[0]`; for the right-most: `[0,1,2,3,4,5,6,7,8,9]`.)

styles:
```
ticker: {
    backgroundColor: 'gray',
    justifyContent: 'center',
    alignItems: 'center'
  },
scoreCommonText: {
    backgroundColor: 'yellow',
    marginTop: 8.0,
    fontFamily: NUNITO_EXTRA_BOLD,
    fontSize: 23.5,
    textAlign: 'center',
    textAlignVertical: 'center'
  },
scoreFirstPlaceText: {
    color: PP_RED
  }
```

<img width="261" alt="screen shot 2018-05-20 at 12 16 56" src="https://user-images.githubusercontent.com/1477963/40277445-bdc17d54-5c27-11e8-9c01-74c3ad1e50e5.png">

**Comment by browniefed** [comment]
v3 rewritten in reanimated and maybe works with this?
